<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Noak-pc" name="test.cli.cloudify.pu.InstallAndUninstallPUTest" tests="3" failures="0" timestamp="1 Mar 2012 08:53:25 GMT" time="630.602" errors="3">
  <testcase name="testMirrorRecipeInstall" time="1.891" classname="test.cli.cloudify.pu.InstallAndUninstallPUTest">
    <error type="java.lang.AssertionError" message="In RunCommand: Process did not complete successfully">
      <![CDATA[java.lang.AssertionError: In RunCommand: Process did not complete successfully
	at org.testng.Assert.fail(Assert.java:89)
	at framework.utils.AssertUtils.AssertFail(AssertUtils.java:97)
	at framework.utils.AssertUtils.AssertFail(AssertUtils.java:89)
	at test.AbstractTest.AssertFail(AbstractTest.java:103)
	at test.cli.cloudify.CommandTestUtils.handleCliOutput(CommandTestUtils.java:111)
	at test.cli.cloudify.CommandTestUtils.runCommand(CommandTestUtils.java:51)
	at test.cli.cloudify.CommandTestUtils.runCommandAndWait(CommandTestUtils.java:123)
	at test.cli.cloudify.pu.InstallAndUninstallPUTest.testRestApiInstall(InstallAndUninstallPUTest.java:52)
	at test.cli.cloudify.pu.InstallAndUninstallPUTest.testMirrorRecipeInstall(InstallAndUninstallPUTest.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
]]>
    </error>
  </testcase>
  <testcase name="testDataGridRecipeInstall" time="316.520" classname="test.cli.cloudify.pu.InstallAndUninstallPUTest">
    <error type="java.lang.AssertionError" message="In RunCommand: Process did not complete successfully">
      <![CDATA[java.lang.AssertionError: In RunCommand: Process did not complete successfully
	at org.testng.Assert.fail(Assert.java:89)
	at framework.utils.AssertUtils.AssertFail(AssertUtils.java:97)
	at framework.utils.AssertUtils.AssertFail(AssertUtils.java:89)
	at test.AbstractTest.AssertFail(AbstractTest.java:103)
	at test.cli.cloudify.CommandTestUtils.handleCliOutput(CommandTestUtils.java:111)
	at test.cli.cloudify.CommandTestUtils.runCommand(CommandTestUtils.java:51)
	at test.cli.cloudify.CommandTestUtils.runCommandAndWait(CommandTestUtils.java:123)
	at test.cli.cloudify.pu.InstallAndUninstallPUTest.testRestApiInstall(InstallAndUninstallPUTest.java:52)
	at test.cli.cloudify.pu.InstallAndUninstallPUTest.testDataGridRecipeInstall(InstallAndUninstallPUTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
]]>
    </error>
  </testcase>
  <testcase name="testStatefulRecipeInstall" time="312.191" classname="test.cli.cloudify.pu.InstallAndUninstallPUTest">
    <error type="java.lang.AssertionError" message="In RunCommand: Process did not complete successfully">
      <![CDATA[java.lang.AssertionError: In RunCommand: Process did not complete successfully
	at org.testng.Assert.fail(Assert.java:89)
	at framework.utils.AssertUtils.AssertFail(AssertUtils.java:97)
	at framework.utils.AssertUtils.AssertFail(AssertUtils.java:89)
	at test.AbstractTest.AssertFail(AbstractTest.java:103)
	at test.cli.cloudify.CommandTestUtils.handleCliOutput(CommandTestUtils.java:111)
	at test.cli.cloudify.CommandTestUtils.runCommand(CommandTestUtils.java:51)
	at test.cli.cloudify.CommandTestUtils.runCommandAndWait(CommandTestUtils.java:123)
	at test.cli.cloudify.pu.InstallAndUninstallPUTest.testRestApiInstall(InstallAndUninstallPUTest.java:52)
	at test.cli.cloudify.pu.InstallAndUninstallPUTest.testStatefulRecipeInstall(InstallAndUninstallPUTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
]]>
    </error>
  </testcase>
</testsuite>
