<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="noak-PC" name="test.cli.cloudify.cloud.byon.KillManagementTest" tests="1" failures="0" timestamp="18 Jul 2012 14:20:53 GMT" time="480.274" errors="1">
  <testcase name="testPetclinic" time="480.274" classname="test.cli.cloudify.cloud.byon.KillManagementTest">
    <error type="java.lang.AssertionError" message="Failed running ssh command: &#039;sudo shutdown now -r&#039; on 192.168.9.133: Remote command failed with exit status 1. SSH output was: sudo: no tty present and no askpass program specified
">
      <![CDATA[java.lang.AssertionError: Failed running ssh command: 'sudo shutdown now -r' on 192.168.9.133: Remote command failed with exit status 1. SSH output was: sudo: no tty present and no askpass program specified

	at org.testng.Assert.fail(Assert.java:78)
	at framework.utils.SSHUtils.runCommand(SSHUtils.java:362)
	at test.cli.cloudify.cloud.byon.KillManagementTest.restartMachine(KillManagementTest.java:164)
	at test.cli.cloudify.cloud.byon.KillManagementTest.restartMachineAndWait(KillManagementTest.java:153)
	at test.cli.cloudify.cloud.byon.KillManagementTest.testPetclinic(KillManagementTest.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
Caused by: Remote command failed with exit status 1
	at org.apache.tools.ant.taskdefs.optional.ssh.SSHExec.executeCommand(SSHExec.java:310)
	at org.apache.tools.ant.taskdefs.optional.ssh.SSHExec.execute(SSHExec.java:194)
	at framework.utils.SSHUtils.runCommand(SSHUtils.java:357)
	... 16 more
]]>
    </error>
  </testcase> <!-- testPetclinic -->
</testsuite> <!-- test.cli.cloudify.cloud.byon.KillManagementTest -->
