<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Noak-pc" name="test.cli.cloudify.PetClinicApplicationTest" tests="1" failures="0" timestamp="5 Jan 2012 15:37:50 GMT" time="148.001" errors="1">
  <testcase name="testPetClinincApplication" time="148.001" classname="test.cli.cloudify.PetClinicApplicationTest">
    <error type="java.lang.AssertionError" message="In RunCommand: Process did not complete successfully">
      <![CDATA[java.lang.AssertionError: In RunCommand: Process did not complete successfully
	at org.testng.Assert.fail(Assert.java:89)
	at framework.utils.AssertUtils.AssertFail(AssertUtils.java:97)
	at framework.utils.AssertUtils.AssertFail(AssertUtils.java:89)
	at test.AbstractTest.AssertFail(AbstractTest.java:103)
	at test.cli.cloudify.CommandTestUtils.handleCliOutput(CommandTestUtils.java:111)
	at test.cli.cloudify.CommandTestUtils.runCommand(CommandTestUtils.java:51)
	at test.cli.cloudify.CommandTestUtils.runCommandAndWait(CommandTestUtils.java:123)
	at test.cli.cloudify.PetClinicApplicationTest.testPetClinincApplication(PetClinicApplicationTest.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase>
</testsuite>
