<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="noak-PC" name="test.cli.cloudify.cloud.byon.MultipleTemplatesWithNamesAsIPsTest" tests="2" failures="1" timestamp="25 Jul 2012 13:25:18 GMT" time="1015.467" errors="1">
  <testcase name="testPetclinicUninstall" time="85.939" classname="test.cli.cloudify.cloud.byon.MultipleTemplatesWithNamesAsIPsTest">
    <error type="java.lang.AssertionError" message="webui is down">
      <![CDATA[java.lang.AssertionError: webui is down
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at framework.utils.AssertUtils._assertTrue(AssertUtils.java:144)
	at framework.utils.AssertUtils.assertTrue(AssertUtils.java:137)
	at framework.utils.AssertUtils.repetitiveAssertTrue(AssertUtils.java:44)
	at test.cli.cloudify.cloud.byon.MultipleMachineTemplatesTest.testPetclinicUninstall(MultipleMachineTemplatesTest.java:224)
	at test.cli.cloudify.cloud.byon.MultipleTemplatesWithNamesAsIPsTest.testPetclinicUninstall(MultipleTemplatesWithNamesAsIPsTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
]]>
    </error>
  </testcase> <!-- testPetclinicUninstall -->
  <testcase name="testPetclinic" time="929.528" classname="test.cli.cloudify.cloud.byon.MultipleTemplatesWithNamesAsIPsTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at test.cli.cloudify.cloud.byon.MultipleMachineTemplatesTest.testPetclinic(MultipleMachineTemplatesTest.java:150)
	at test.cli.cloudify.cloud.byon.MultipleTemplatesWithNamesAsIPsTest.testPetclinic(MultipleTemplatesWithNamesAsIPsTest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
]]>
    </failure>
  </testcase> <!-- testPetclinic -->
</testsuite> <!-- test.cli.cloudify.cloud.byon.MultipleTemplatesWithNamesAsIPsTest -->
