<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="noak-PC" name="test.cli.cloudify.cloud.hp.HPExamplesTest" tests="2" failures="2" timestamp="25 Jul 2012 12:06:16 GMT" time="0.002" errors="0">
  <testcase name="testPetclinic" time="0.001" classname="test.cli.cloudify.cloud.hp.HPExamplesTest">
    <failure type="java.lang.AssertionError" message="Bootstrapping of cloud (hp, HPExamplesTest) failed with the following error: com.sun.jersey.api.client.UniformInterfaceException: GET https://az-2.region-a.geo-1.compute.hpcloudsvc.com/v1.1/24912589714038/servers/344149 returned a response status of 404 Not Found">
      <![CDATA[java.lang.AssertionError: Bootstrapping of cloud (hp, HPExamplesTest) failed with the following error: com.sun.jersey.api.client.UniformInterfaceException: GET https://az-2.region-a.geo-1.compute.hpcloudsvc.com/v1.1/24912589714038/servers/344149 returned a response status of 404 Not Found
	at org.testng.Assert.fail(Assert.java:78)
	at framework.utils.AssertUtils.AssertFail(AssertUtils.java:100)
	at test.AbstractTestSupport.AssertFail(AbstractTestSupport.java:68)
	at test.cli.cloudify.cloud.NewAbstractCloudTest.bootstrap(NewAbstractCloudTest.java:148)
	at test.cli.cloudify.cloud.hp.HPExamplesTest.bootstrap(HPExamplesTest.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:551)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1022)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:109)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:202)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:173)
Caused by: java.io.IOException: com.sun.jersey.api.client.UniformInterfaceException: GET https://az-2.region-a.geo-1.compute.hpcloudsvc.com/v1.1/24912589714038/servers/344149 returned a response status of 404 Not Found
	at test.cli.cloudify.cloud.services.AbstractCloudService.bootstrapCloud(AbstractCloudService.java:266)
	at test.cli.cloudify.cloud.NewAbstractCloudTest.bootstrap(NewAbstractCloudTest.java:146)
	... 25 more
Caused by: com.sun.jersey.api.client.UniformInterfaceException: GET https://az-2.region-a.geo-1.compute.hpcloudsvc.com/v1.1/24912589714038/servers/344149 returned a response status of 404 Not Found
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:676)
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.get(WebResource.java:503)
	at test.cli.cloudify.cloud.services.tools.openstack.OpenstackClient.getNode(OpenstackClient.java:152)
	at test.cli.cloudify.cloud.services.tools.openstack.OpenstackClient.listServers(OpenstackClient.java:198)
	at test.cli.cloudify.cloud.services.hp.HpCloudService.beforeBootstrap(HpCloudService.java:105)
	at test.cli.cloudify.cloud.services.AbstractCloudService.bootstrapCloud(AbstractCloudService.java:241)
	... 26 more
]]>
    </failure>
  </testcase> <!-- testPetclinic -->
  <testcase name="testTravel" time="0.001" classname="test.cli.cloudify.cloud.hp.HPExamplesTest">
    <failure type="java.lang.AssertionError" message="Bootstrapping of cloud (hp, HPExamplesTest) failed with the following error: com.sun.jersey.api.client.UniformInterfaceException: GET https://az-2.region-a.geo-1.compute.hpcloudsvc.com/v1.1/24912589714038/servers/344149 returned a response status of 404 Not Found">
      <![CDATA[java.lang.AssertionError: Bootstrapping of cloud (hp, HPExamplesTest) failed with the following error: com.sun.jersey.api.client.UniformInterfaceException: GET https://az-2.region-a.geo-1.compute.hpcloudsvc.com/v1.1/24912589714038/servers/344149 returned a response status of 404 Not Found
	at org.testng.Assert.fail(Assert.java:78)
	at framework.utils.AssertUtils.AssertFail(AssertUtils.java:100)
	at test.AbstractTestSupport.AssertFail(AbstractTestSupport.java:68)
	at test.cli.cloudify.cloud.NewAbstractCloudTest.bootstrap(NewAbstractCloudTest.java:148)
	at test.cli.cloudify.cloud.hp.HPExamplesTest.bootstrap(HPExamplesTest.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:551)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1022)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:109)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:202)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:173)
Caused by: java.io.IOException: com.sun.jersey.api.client.UniformInterfaceException: GET https://az-2.region-a.geo-1.compute.hpcloudsvc.com/v1.1/24912589714038/servers/344149 returned a response status of 404 Not Found
	at test.cli.cloudify.cloud.services.AbstractCloudService.bootstrapCloud(AbstractCloudService.java:266)
	at test.cli.cloudify.cloud.NewAbstractCloudTest.bootstrap(NewAbstractCloudTest.java:146)
	... 25 more
Caused by: com.sun.jersey.api.client.UniformInterfaceException: GET https://az-2.region-a.geo-1.compute.hpcloudsvc.com/v1.1/24912589714038/servers/344149 returned a response status of 404 Not Found
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:676)
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.get(WebResource.java:503)
	at test.cli.cloudify.cloud.services.tools.openstack.OpenstackClient.getNode(OpenstackClient.java:152)
	at test.cli.cloudify.cloud.services.tools.openstack.OpenstackClient.listServers(OpenstackClient.java:198)
	at test.cli.cloudify.cloud.services.hp.HpCloudService.beforeBootstrap(HpCloudService.java:105)
	at test.cli.cloudify.cloud.services.AbstractCloudService.bootstrapCloud(AbstractCloudService.java:241)
	... 26 more
]]>
    </failure>
  </testcase> <!-- testTravel -->
</testsuite> <!-- test.cli.cloudify.cloud.hp.HPExamplesTest -->
