<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="noak-PC" name="Clouds Test" tests="3" failures="0" timestamp="22 Jul 2012 14:45:28 GMT" time="0.045" errors="0">
  <testcase name="@AfterClass afterClass" time="0.0" classname="test.cli.cloudify.cloud.MyTestA">
    <failure type="java.lang.AssertionError" message="Failing the after class">
      <![CDATA[java.lang.AssertionError: Failing the after class
	at framework.utils.AssertUtils.AssertFail(AssertUtils.java:102)
	at framework.utils.AssertUtils.AssertFail(AssertUtils.java:94)
	at test.cli.cloudify.cloud.MyAbstractClass.afterClass(MyAbstractClass.java:43)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- @AfterClass afterClass -->
  <testcase name="@BeforeMethod beforeMethod" time="0.0" classname="test.cli.cloudify.cloud.MyTestB">
    <skipped/>
  </testcase> <!-- @BeforeMethod beforeMethod -->
  <testcase name="@AfterMethod afterMethod" time="0.0" classname="test.cli.cloudify.cloud.MyTestB">
    <skipped/>
  </testcase> <!-- @AfterMethod afterMethod -->
  <testcase name="@AfterClass afterClass" time="0.0" classname="test.cli.cloudify.cloud.MyTestB">
    <skipped/>
  </testcase> <!-- @AfterClass afterClass -->
  <testcase name="@AfterTest afterTest" time="0.0" classname="test.cli.cloudify.cloud.MyTestA">
    <skipped/>
  </testcase> <!-- @AfterTest afterTest -->
  <testcase name="testMethod1" time="0.0050" classname="test.cli.cloudify.cloud.MyTestA"/>
  <testcase name="testMethod2" time="0.0" classname="test.cli.cloudify.cloud.MyTestA"/>
  <testcase name="testMethod" time="0.0010" classname="test.cli.cloudify.cloud.MyTestB">
    <skipped/>
  </testcase> <!-- testMethod -->
</testsuite> <!-- Clouds Test -->
